// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCAao8ngFE1lE3CsCeTLSIt5kW_jbHfME',
    appId: '1:679133340512:web:a3dc4aeb81c3baca017405',
    messagingSenderId: '679133340512',
    projectId: 'lab8-9ae65',
    authDomain: 'lab8-9ae65.firebaseapp.com',
    storageBucket: 'lab8-9ae65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC80-qXJu2hPGNVDXfzGqfoY47J0J2U_10',
    appId: '1:679133340512:android:860966ee518ceaa9017405',
    messagingSenderId: '679133340512',
    projectId: 'lab8-9ae65',
    storageBucket: 'lab8-9ae65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhZ3BFmkAJTtAb-ZHsb3gu2qjibuognKs',
    appId: '1:679133340512:ios:ec41fc6b3370d660017405',
    messagingSenderId: '679133340512',
    projectId: 'lab8-9ae65',
    storageBucket: 'lab8-9ae65.firebasestorage.app',
    iosClientId: '679133340512-t2m4o0mle83lp6shj3uanr91au6b9j8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhZ3BFmkAJTtAb-ZHsb3gu2qjibuognKs',
    appId: '1:679133340512:ios:ec41fc6b3370d660017405',
    messagingSenderId: '679133340512',
    projectId: 'lab8-9ae65',
    storageBucket: 'lab8-9ae65.firebasestorage.app',
    iosClientId: '679133340512-t2m4o0mle83lp6shj3uanr91au6b9j8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCAao8ngFE1lE3CsCeTLSIt5kW_jbHfME',
    appId: '1:679133340512:web:94147aa5cf116853017405',
    messagingSenderId: '679133340512',
    projectId: 'lab8-9ae65',
    authDomain: 'lab8-9ae65.firebaseapp.com',
    storageBucket: 'lab8-9ae65.firebasestorage.app',
  );
}
